[webHookConfig]
token = ""   # 机器人token
address = "localhost:8080"  # 服务地址
domain = ""   # 内网穿透后的外网域名
secret = ""  # 任意字符串，可留空，由程序自动生成

[log]
timeFormat = ""  # 可留空
path = ""  # 留空表示不记录
level = 0 # zero log 等级 0是最低

[ytdlp]
path = "" # default: yt-dlp
